spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/auth_data
    driverClassName: org.h2.Driver
    username: sa

server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
